### ISSUE TITLE
Rails 7.1.0 update leads to no warden strategies being found ?

### ISSUE THREAD

**Issue by jwoodrow** [heartcombo/devise#5637] opened 2023-10-08 11:48 UTC
## Environment

- Ruby 3.2.2
- Rails 7.1.0
- Devise 4.9.2 & main branch

## Current behavior

I was trying to upgrade our rails app to Rails 7.1.0 and now when I try to access a page requiring authentication I get a `RuntimeError` `Invalid strategy trackable` on a model that has nothing to do with the one being require for that specific page (`Admin` for our admin panel and `User` for our frontend).

Commenting out the `devise :database_authenticatable, :confirmable, :registerable, :recoverable, :trackable, :validatable` in the `User` model then makes the same error appear but this time for `Admin` and commenting out the `device :trackable` in that model then leads to a `undefined method 'authentication_keys' for Admin:Class` (which kind of makes sense after removing basically both devise calls on both models)

I don't know if this is specifically related to Rails 7.1.0 but for extra context we also do have 3 custom strategies setup but they don't seem to be causing any interference.

The error occurs here `Warden::Proxy#_fetch_strategy`

and if I use `better_errors` to print out the value for `@strategies` I get this as a result `{:user=>{}}` almost as if no strategies at all existed

## Expected behavior

Arrive on the login page with no errors

**Comment by gagoit** [comment] 2023-10-09 03:22
I also faced to this issue, and I saw that came from this [change](https://github.com/rails/rails/commit/43b980368a7628fac95cc4f673e0dfbcee77c10b). The hash#deep_merge has been changed behavior:
- In rails 7.0.8
![Screenshot 2023-10-09 at 09 59 18](https://github.com/heartcombo/devise/assets/3380093/ab628dc5-1c17-4226-8bb1-e29f60a94ce3)

- In rails 7.1.0
![Screenshot 2023-10-09 at 09 59 25](https://github.com/heartcombo/devise/assets/3380093/f9b7d2d5-5502-4273-a1bc-d1d37e8ee74f)

So when we use [Devise.with_options](https://github.com/heartcombo/devise/blob/main/lib/devise/modules.rb#L5) with multiple blocks inside (for adding multiple modules), the options that passed to each module has been merged, that make the `Devise::STRATEGIES` has been changed in-correctly => warden has failed to load the incorrect strategies

NOTE:
- In rails 7.0.8, the Devise::STRATEGIES won't include `trackable, timeoutable, lockable...`
- In rails 7.1.0, the Devise::STRATEGIES will include `trackable, timeoutable, lockable...`

**Comment by carlosantoniodasilva** [comment] 2023-10-10 12:50
@gagoit I'm not able to replicate this on a brand new 7.1 app:

<img width="551" alt="Screenshot 2023-10-10 at 09 48 44" src="https://github.com/heartcombo/devise/assets/26328/b5d5c22a-8fc2-4e04-815c-d8ce4e34afc1">

I'm still looking, it's possible something fundamental has changed somewhere, but wanted to mention the above in case I'm missing something from your example. Thanks.

**Comment by gagoit** [comment] 2023-10-10 15:48
@carlosantoniodasilva Thanks for your info.
I've checked the other gems in my project, and saw it's related to the [config](https://github.com/rubyconfig/config) gem (more details here https://github.com/rails/rails/issues/49457 and https://github.com/rubyconfig/config/pull/342). 

Summary:
Config gem uses [deep_merge](https://github.com/danielsdeleo/deep_merge) and DeepMerge's Hash monkey patch is not compatible with Rails 7.1 (see https://github.com/rails/rails/issues/49457).
=> that make the behavior of `deep_merge` is changed in my project
=> [Devise.with_options](https://github.com/heartcombo/devise/blob/main/lib/devise/modules.rb#L5) doesn't work correctly.

Sorry for making you confuse.

**Comment by carlosantoniodasilva** [comment] 2023-10-10 16:19
@gagoit thanks for the feedback, glad to know the issue is elsewhere :)

@jwoodrow are you also using the same `config` gem? It sounds like this could be the culprit.

I tested a brand new app with devise (using this newly created 4-stable branch which contains tweaks for Rails 7.1), and everything appears to be working. If anyone would like to give that a try, let me know if you run into any issues.

**Comment by jwoodrow** [comment] 2023-10-10 18:48
@carlosantoniodasilva We are indeed using the config gem, guessing the culprit must be there. Thanks to both of you for looking into this and finding the culprit. Now the question for me is, do I truly still need this gem :D

**Comment by carlosantoniodasilva** [comment] 2023-10-10 18:53
Thanks for reporting back. I'll consider this one as closed then for now, but please report back if you run into anything else.

**Closed by carlosantoniodasilva** 2023-10-10 18:53 UTC

**Comment by saxxi** [comment] 2024-01-26 14:21
Thanks for the heads up, for other users:

In order to update rails from `7.0` to `7.1` I had to manually upgrade [config](https://github.com/rubyconfig/config) gem (from `4.1` to `5.1` in my case) which stopped the error `Invalid strategy trackable` (was giving error for all strategies, not just `trackable`).
